--=======================================
-- Dimension Exploration
-- Indentify the unique values in each dimension
-- Recognise how data might be grouped or segmented
-- Useful for later analysis
--=======================================

-- Looking at gold.dim_customers countries

SELECT DISTINCT
country
FROM gold.dim_customers

-- Looking at the "major divisions"
SELECT DISTINCT
category,
subcategory,
product_name
FROM gold.dim_products
ORDER BY 1,2,3

--=======================================
-- DATE Exploration
-- Indentify the earliest and latest dates (boundaries)
-- understand the timespan
-- Useful for later analysis
--=======================================

-- Using fact_sales
-- Looking at first and last orders
SELECT MIN(order_date) AS first_order_date,
MAX(order_date) AS latest_order_date,
DATEDIFF(YEAR, MIN(order_date) , MAX(order_date)) AS year_diff
FROM gold.fact_sales

-- Looking at the youngest and the oldest customers
SELECT
MIN(birthdate) AS oldest_bisthdate,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(YEAR, MIN(birthdate), MAX(birthdate)) AS age_diff
FROM gold.dim_customers

--=======================================
-- Measures Exploration
-- Calculate the key metrices of the business
-- understand the unique values of the dimension coluns
-- Useful for later analysis like SUM, AVG 
--=======================================

-- Find the Total Sales
SELECT SUM(sales) AS total_sales FROM gold.fact_sales; -- $29,356,250

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales; -- 60423

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales; -- $486

-- Find the Total number of Orders
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales; -- 27659 orders

-- Find the total number of Customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers; -- 18484 unique customers

-- Find the total number of Products
SELECT COUNT(product_name) AS total_products FROM gold.dim_products;
SELECT COUNT(DISTINCT product_name) AS total_products FROM gold.dim_products; -- 295 PRODUCTS


-- Find the total number of custoemrs that have placed orders
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.dim_customers; -- 18484 unique customers


-- Building a Summary table of the values
SELECT 'Total Sales' AS measure_name,  FORMAT(SUM(sales), 'C') AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders Sold' AS measure_name, CAST(SUM(quantity) AS varchar(20)) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name,  FORMAT(AVG(sales), 'C') AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders' AS measure_name, CAST(COUNT(DISTINCT order_number) AS varchar(20)) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Customers' AS measure_name, CAST(COUNT(customer_key) AS varchar(20)) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total Products' AS measure_name, CAST(COUNT(DISTINCT product_name) AS varchar(20)) AS measure_value FROM gold.dim_products;

--=======================================
-- Magnitude Analysis
-- Comparing the measure values by categories
-- Helps to understand the importance of different categories
--=======================================

-- Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find the total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find the total customers by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category 
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
category,
FORMAT(AVG(cost), 'C') AS avg_cost 
FROM gold.dim_products
GROUP BY category 
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
p.category,
FORMAT(SUM(f.sales), 'C') AS total_revenue 
FROM gold.fact_sales f
LEFT JOIN gold.dim_products P
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY SUM(f.sales) DESC;

-- Find total revenue generated by each customer
SELECT
    c.customer_key AS customer_key,
    c.first_name,
    c.last_name,
    FORMAT(SUM(f.sales), 'C') AS total_spend
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY
    SUM(f.sales) DESC;

-- What is the distribution of sold items acoss countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.country
ORDER BY
    SUM(f.quantity) DESC;

-- Total revenue by by gender
SELECT
c.gender,
FORMAT(SUM(f.sales), 'C') AS total_revenue 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.gender
ORDER BY SUM(f.sales) DESC;


--=======================================
-- Ranking Analysis
-- Order the values by dimensions to find the top and bottom performers
-- Helps to identify the best and worst performing categories and customers
--=======================================

-- Which 5 products have generated the most revenue?

SELECT TOP 5
    p.product_name,
    FORMAT(SUM(f.sales), 'C') AS total_revenue
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key
        GROUP BY p.product_name
        ORDER BY SUM(f.sales) DESC;

-- What are the 5 worst performing products in terms of revenue?
SELECT TOP 5
    p.product_name,
    FORMAT(SUM(f.sales), 'C') AS total_revenue
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key
        GROUP BY p.product_name
        ORDER BY SUM(f.sales) ASC;

-- What are the top 5 performing products bought by gender
SELECT TOP 5
    c.gender,
    p.product_name,
    FORMAT(SUM(f.sales), 'C') AS total_revenue
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
    LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
    WHERE c.gender = 'Female'
    GROUP BY 
        c.gender,
        p.product_name
    ORDER BY SUM(f.sales) DESC;

--===================================
-- Using Window Functions
--===================================
    
-- What are the top 5 performing products bought by Country -- Substitute country in WHERE clause

SELECT
    p.product_name,
    FORMAT(SUM(f.sales), 'C') AS total_revenue,
    ROW_NUMBER() OVER(ORDER BY SUM(f.sales) DESC) AS rank_proucts
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
    LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
    WHERE c.country = 'United States'
    GROUP BY 
        p.product_name;

-- What are the 5 worst performing products in terms of revenue?
SELECT 
    p.product_name,
    FORMAT(SUM(f.sales), 'C') AS total_revenue,
    ROW_NUMBER() OVER (ORDER BY SUM(f.sales) DESC) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key
        GROUP BY p.product_name

-- Getting top 5
SELECT TOP 5 *
FROM (
SELECT 
    p.product_name,
    FORMAT(SUM(f.sales), 'C') AS total_revenue,
    ROW_NUMBER() OVER (ORDER BY SUM(f.sales) DESC) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key
        GROUP BY p.product_name
)t
